### ISSUE TITLE
[Bug]: `react/jsx-no-literals` crashes with `Cannot read properties of null (reading 'type')`

### ISSUE THREAD

**Issue by reosarevok** [jsx-eslint/eslint-plugin-react#3822]
### Is there an existing issue for this?

- [X] I have searched the existing issues and my issue is unique
- [X] My issue appears in the command-line and not only in the text editor

### Description Overview

Trying the latest v7.36.0 version of the plugin, we're seeing crashes such as:

```
Oops! Something went wrong! :(

ESLint: 8.57.0

TypeError: Cannot read properties of null (reading 'type')
Occurred while linting /home/reosarevok/musicbrainz-server/root/annotation/AnnotationHistory.js:32
Rule: "react/jsx-no-literals"
    at JSXAttribute (/home/reosarevok/musicbrainz-server/node_modules/eslint-plugin-react/lib/rules/jsx-no-literals.js:508:44)
    at ruleErrorHandler (/home/reosarevok/musicbrainz-server/node_modules/eslint/lib/linter/linter.js:1076:28)
    at /home/reosarevok/musicbrainz-server/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/reosarevok/musicbrainz-server/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/reosarevok/musicbrainz-server/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/home/reosarevok/musicbrainz-server/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/home/reosarevok/musicbrainz-server/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/home/reosarevok/musicbrainz-server/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:803:23)
    at /home/reosarevok/musicbrainz-server/node_modules/eslint/lib/linter/linter.js:1111:32

```

That specific line is `fullWidth` in 

```
    <LayoutComponent
      entity={entity}
      fullWidth
      page="annotation-history"
      title={l('Annotation history')}
    >
```

The failure seems to be due to https://github.com/jsx-eslint/eslint-plugin-react/commit/b8217ed5f4104bd18b54f77ea108ec081ebbbd49 removing the `node && node.value &&` checks from the new `isLiteralString` and `isStringLiteral` calculations, which were present in the previous `isNodeValueString`. Just changing both those checks to do `node.value?.type` fixes the issue, and it seems like it should be safe, but you might want to make sure (happy to send a PR if that's the case).

### Expected Behavior

The plugin should not crash and should understand there's no issue with this code.

### eslint-plugin-react version

v7.36.0

### eslint version

v8.57.0

### node version

v22.8.0

**Comment by reosarevok** [comment]
Seems this got reported while I was writing it, as https://github.com/jsx-eslint/eslint-plugin-react/issues/3820 :)
